# Generated by Django 4.0.3 on 2022-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
