# Generated by Django 4.0.3 on 2022-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_serviceappointment_vip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='automobile',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vin',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
