# Generated by Django 4.0.3 on 2022-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_remove_serviceappointment_automobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_time',
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
    ]
