# Generated by Django 4.0.3 on 2022-10-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_serviceappointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='appointment_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
