# Generated by Django 4.0.3 on 2022-10-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_serviceappointment_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='appointment_time',
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
    ]
