# Generated by Django 4.0.3 on 2022-10-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
    ]
