# Generated by Django 4.0.3 on 2022-10-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_delete_status_serviceappointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceappointment',
            old_name='status',
            new_name='service_status',
        ),
    ]
